### ISSUE TITLE
Runtime exception for version 4.1.1 due to latest fix - Wrap every command argument in quotes

### ISSUE THREAD

**Issue by amardeokar23** [mhor/php-mediainfo#87]
Fatal error: Uncaught RuntimeException in /vendor/mhor/php-mediainfo/src/Runner/MediaInfoCommandRunner.php:98
Stack trace:
#0 /vendor/mhor/php-mediainfo/src/MediaInfo.php(37): Mhor\MediaInfo\Runner\MediaInfoCommandRunner->run()
#1 /test.php(21): Mhor\MediaInfo\MediaInfo->getInfo('/tmp/300x250.jp...')
#2 {main}
  thrown in /vendor/mhor/php-mediainfo/src/Runner/MediaInfoCommandRunner.php on line 98

**Comment by amardeokar23** [comment]
Wrong placement of double quotes. Code should be like below.

```
@@ -71,7 +71,7 @@ public function __construct(
         $i = 0;
         foreach ($args as $value) {
             $var = 'MEDIAINFO_VAR_'.$i++;
-            $finalCommand[] = '$"'.$var.'"';
+            $finalCommand[] = '"$'.$var.'"';
             $env[$var] = $value;
         }
```

**Comment by mhor** [comment]
@amardeokar23 Thanks for reporting this issue. Could you create a PR with your patch please ?
